### ISSUE TITLE
from until parsing

### ISSUE THREAD

**Issue by monWork** [zoho/hawking#20]
Hi,
 I was the demo on few scenarios and for some reason durations arent able to come correctedly.
For example:
Input = "He worked in Google from 2012 to 2020."
expected output should have duration from 2012 to 2020 captured together.
However, actual output = 
Jul 10, 2021 2:50:39 AM com.zoho.hawking.utils.DateTimeProperties emptyDatesRemover
INFO: DateTimeExtractor :: Unparsed date is present :: to 2020
Label : D
Text : from 2012
IsTimeZonePresent : false
Time Zone : +00:00
IsExactTimePresent : false
Id : 0
End Index : 29
Start Index : 20
Match Type : 
Start : 2011-12-31T19:00:00.000-05:00
End : null
Sequence :MULTIPLE
Expression :(0)between(1)

to 2020 is unpared. 

Similarly, if sentences has multiple examples with , separated if picks only partial either start date or end date but complete start and end date together.

**Comment by ArulVendhan** [comment]
we are working on the issue. will update once fixed... let us know if there are any other cases too ..

**Comment by ArulVendhan** [comment]
we have fixed the issue stated @monWork , pull the latest master for those changes. maven release is in process, v0.1.4 will have those changes

**Comment by monWork** [comment]
its still the same:
input : He also served as a Vice President for Google from May 2012 to October 2014, and Chief Executive Officer, President and Director of Facebook from March 2007 to June 2011.

output : 
INFO: Label : D
Text : from May 2012
IsTimeZonePresent : false
Time Zone : +05:30
IsExactTimePresent : false
Id : 0
End Index : 59
Start Index : 46
Match Type : 
Start : 2012-04-30T14:30:00.000-04:00
End : null
Label : D
Text : to October 2014
IsTimeZonePresent : false
Time Zone : +05:30
IsExactTimePresent : false
Id : 1
End Index : 75
Start Index : 60
Match Type : 
Start : 2014-09-30T14:30:00.000-04:00
End : 2014-10-31T14:29:59.000-04:00
Label : D
Text : from March 2007
IsTimeZonePresent : false
Time Zone : +05:30
IsExactTimePresent : false
Id : 0
End Index : 156
Start Index : 141
Match Type : 
Start : 2007-02-28T13:30:00.000-05:00
End : null
Label : D
Text : to June 2011
IsTimeZonePresent : false
Time Zone : +05:30
IsExactTimePresent : false
Id : 1
End Index : 169
Start Index : 157
Match Type : 
Start : 2011-05-31T14:30:00.000-04:00
End : 2011-06-30T14:29:59.000-04:00
Sequence :MULTIPLE
Expression :(0)between(1)
Sequence :MULTIPLE
Expression :(0)between(1)
Sequence :MULTIPLE
Expression :(0)between(1)
Sequence :MULTIPLE
Expression :(0)between(1)


Start and end time should be from start date to end date, right ?

**Comment by monWork** [comment]
@ArulVendhan isnt it supposed to be like that or the current output is expected output ?

**Comment by ArulVendhan** [comment]
Hi @monWork , its not need to be like that, that depends on the user preference
"from May 2012 to October 2014 "

prefix **"from"** represents to start date of the span so Hawking returns only start date..

for example: **" from last Sunday"** --> refers only to start date, it cant assign end date as today because it can be an ongoing event or not..  other prefixes that indicate only start date: **" since, after, starting from, beginning from "** so hawking will return only start date for all date text with these prefixes, it cant assume end date as it may vary from user to user. 

**"to October 2014 "**
Here **"to"** returns both start and end date of the month because, 
sometimes "to" refers end of the October  or start of October that's based on user preference to, so Hawking returns both start and end date of that month ...


User can use the **"Id, Sequence , Expression"** from Datesfound to find whether that date has any relation with other date and user can pick end date or start date of **"to October 2014 "** based on their need.

For Single date
Sequence: **SINGLE**
Expression: (0)

Different Expressions returned for relation dates from hawking : 
sample : **"from Monday to Friday/Monday and Tuesday/Monday or Tuesday"**
Sequence :**MULTIPLE**
Expression :**(0)between(1)** / **(0)and(1)** / **(0)or(1)**

Hope this clears your doubt why there is a start date and end date for **October 2014/ to June 2011** and how the user can use the expression from DatesFound object to connect 2 relation dates.

Soon we are going to update a doc that has use-cases and output response, reason, and how users can use hawking output.
